# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accepted_invitations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='guest_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='pending_invitations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unaccepted_invitations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
